# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[ïŸ ](fg:bright-purple)"
error_symbol = "[ïŸ ](bright-red)"
vimcmd_symbol = "[ïŸ” ](fg:bright-purple)"

[username]
show_always = true
style_user = "bold bright-black"

[directory]
style = "bold blue"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
disabled = true

[java]
symbol = 'â˜• '

[perl]
symbol = 'ğŸ’  '
detect_extensions = ['pl', 'pod']
